// Builds src/playbook/generated.ts from the playbook files and the View Type
// definitions (docs/view-types/*.md, part of the spec). Pure: the script
// (scripts/build-playbook.ts) and the drift test read the files and pass them in.
//
// The Workers runtime has no file system, so the prompts ship as a generated
// module rather than being read at run time.

/** One View Type as the skim sees it (spec §5.2: its `answers`, "Draws on" and "Building it from a source"). */
export type CatalogEntry = {
  id: string
  name: string
  status: "proven" | "experimental"
  answers: string
  drawsOn: string
  fromSource: string
}

type Doc = { meta: Record<string, string>; sections: Map<string, string> }

function parseDoc(md: string): Doc {
  const text = md.replace(/\r\n/g, "\n")
  const fm = /^---\n([\s\S]*?)\n---\n?/.exec(text)
  const meta: Record<string, string> = {}
  for (const line of fm?.[1]?.split("\n") ?? []) {
    const m = /^([\w-]+):\s*(.*)$/.exec(line)
    if (m) meta[m[1]!] = m[2]!.replace(/^"(.*)"$/, "$1").trim()
  }
  const sections = new Map<string, string>()
  const body = text.slice(fm ? fm[0].length : 0)
  const parts = body.split(/^## /m).slice(1)
  for (const part of parts) {
    const nl = part.indexOf("\n")
    sections.set(part.slice(0, nl).trim(), part.slice(nl + 1).trim())
  }
  return { meta, sections }
}

/**
 * The catalog from the View Type files (name → markdown). Only proven and
 * experimental View Types; candidates (their own folder) and the template
 * never reach it. Sorted by id so the output is stable.
 */
export function buildCatalog(files: Record<string, string>): CatalogEntry[] {
  const out: CatalogEntry[] = []
  for (const [name, md] of Object.entries(files)) {
    if (name.startsWith("_") || name === "README.md") continue
    const { meta, sections } = parseDoc(md)
    // "proven (idea); rendering needs …" is proven: the first word counts.
    const status = /^\w+/.exec(meta.status ?? "")?.[0]
    if (status !== "proven" && status !== "experimental") continue
    const id = meta.id ?? name.replace(/\.md$/, "")
    const drawsOn = sections.get("Draws on")
    const fromSource = sections.get("Building it from a source")
    if (!meta.name || !meta.answers || !drawsOn || !fromSource)
      throw new Error(
        `docs/view-types/${name}: needs name, answers, "Draws on" and "Building it from a source"`
      )
    out.push({ id, name: meta.name, status, answers: meta.answers, drawsOn, fromSource })
  }
  return out.sort((a, b) => a.id.localeCompare(b.id))
}

/** A playbook file as a prompt: without its leading HTML comment. */
export function promptText(md: string): string {
  return md
    .replace(/\r\n/g, "\n")
    .replace(/^\s*<!--[\s\S]*?-->\s*/, "")
    .trim()
}

/** The generated module's source. */
export function generatedModule(args: {
  skim: string
  viewTypes: Record<string, string>
}): string {
  const catalog = buildCatalog(args.viewTypes)
  return [
    "// Generated by scripts/build-playbook.ts from packages/ai/playbook/ and",
    "// docs/view-types/. Do not edit: change those files and run",
    "// `pnpm --filter @seply/ai playbook`.",
    'import type { CatalogEntry } from "./source.ts"',
    "",
    `export const SKIM_PROMPT = ${JSON.stringify(promptText(args.skim))}`,
    "",
    `export const VIEW_TYPE_CATALOG: readonly CatalogEntry[] = ${JSON.stringify(catalog, null, 2)}`,
    "",
  ].join("\n")
}
